#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.3.2 effective-5.10 (swiftlang-6.3.2.1.108 clang-2100.1.1.101)
#ifndef TAGSDK_SWIFT_H
#define TAGSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="TagSdk",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="TagSdk",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class TagCustomerBindingRequest;
@protocol TagCustomerBindingCompletion;
SWIFT_PROTOCOL("_TtP6TagSdk22CustomerBindingHandler_")
@protocol CustomerBindingHandler
- (void)bind:(TagCustomerBindingRequest * _Nonnull)request completion:(id <TagCustomerBindingCompletion> _Nonnull)completion;
@end

@class NSString;
@class TagLoginCapabilities;
@class TagBatteryInfo;
SWIFT_CLASS("_TtC6TagSdk16FindDeviceResult")
@interface FindDeviceResult : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull scanDeviceId;
@property (nonatomic, readonly) BOOL triggered;
@property (nonatomic, readonly, strong) TagLoginCapabilities * _Nullable capabilities;
@property (nonatomic, readonly, strong) TagBatteryInfo * _Nullable battery;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSCoder;
SWIFT_CLASS("_TtC6TagSdk10TagAccount")
@interface TagAccount : NSObject <NSSecureCoding>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL supportsSecureCoding;)
+ (BOOL)supportsSecureCoding SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull accountId;
@property (nonatomic, readonly, copy) NSString * _Nonnull username;
@property (nonatomic, readonly, copy) NSString * _Nullable nickname;
@property (nonatomic, readonly, copy) NSString * _Nullable email;
- (nonnull instancetype)initWithAccountId:(NSString * _Nonnull)accountId username:(NSString * _Nonnull)username nickname:(NSString * _Nullable)nickname email:(NSString * _Nullable)email OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)coder;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC6TagSdk14TagBatteryInfo")
@interface TagBatteryInfo : NSObject
@property (nonatomic, readonly) NSInteger rawBattery;
@property (nonatomic, readonly) NSInteger serverLevel;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class TagDeviceKey;
SWIFT_CLASS("_TtC6TagSdk14TagBindingInfo")
@interface TagBindingInfo : NSObject
@property (nonatomic, readonly, strong) TagDeviceKey * _Nonnull primaryDeviceKey;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, TagBluetoothState, open) {
  TagBluetoothStateUnknown = 0,
  TagBluetoothStatePoweredOff = 1,
  TagBluetoothStatePoweredOn = 2,
  TagBluetoothStateUnauthorized = 3,
};

SWIFT_PROTOCOL("_TtP6TagSdk25TagBluetoothStateListener_")
@protocol TagBluetoothStateListener
- (void)onStateChanged:(enum TagBluetoothState)state;
@end

@class TagCustomerBindingDecision;
SWIFT_PROTOCOL("_TtP6TagSdk28TagCustomerBindingCompletion_")
@protocol TagCustomerBindingCompletion
- (void)complete:(TagCustomerBindingDecision * _Nonnull)decision;
@end

@class TagCustomerBindingError;
SWIFT_CLASS("_TtC6TagSdk26TagCustomerBindingDecision")
@interface TagCustomerBindingDecision : NSObject
@property (nonatomic, readonly) BOOL isApproved;
@property (nonatomic, readonly, strong) TagCustomerBindingError * _Nullable error;
+ (TagCustomerBindingDecision * _Nonnull)approved SWIFT_WARN_UNUSED_RESULT;
+ (TagCustomerBindingDecision * _Nonnull)rejected:(TagCustomerBindingError * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSError;
SWIFT_CLASS("_TtC6TagSdk23TagCustomerBindingError")
@interface TagCustomerBindingError : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable message;
@property (nonatomic, readonly, strong) NSError * _Nullable platformCause;
- (nonnull instancetype)initWithMessage:(NSString * _Nullable)message platformCause:(NSError * _Nullable)platformCause OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC6TagSdk25TagCustomerBindingRequest")
@interface TagCustomerBindingRequest : NSObject
@property (nonatomic, readonly, strong) TagBindingInfo * _Nonnull bindingInfo;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC6TagSdk9TagDevice")
@interface TagDevice : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic, readonly, copy) NSString * _Nullable name;
@property (nonatomic, readonly) NSInteger rssi;
@property (nonatomic, readonly, copy) NSString * _Nullable platformAddress;
@property (nonatomic, readonly, copy) NSString * _Nullable advertisedMac;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSNumber;
SWIFT_CLASS("_TtC6TagSdk13TagDeviceData")
@interface TagDeviceData : NSObject
@property (nonatomic, readonly, strong) TagDeviceKey * _Nonnull deviceKey;
@property (nonatomic, readonly) int64_t collectionTimeMs;
@property (nonatomic, readonly) double longitude;
@property (nonatomic, readonly) double latitude;
@property (nonatomic, readonly, strong) NSNumber * _Nullable batteryLevel;
@property (nonatomic, readonly, strong) NSNumber * _Nullable accuracyLevel;
@property (nonatomic, readonly) BOOL googleLocation;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, TagDeviceDataPreset, open) {
  TagDeviceDataPresetLatest = 0,
  TagDeviceDataPresetLast1Hour = 1,
  TagDeviceDataPresetLast2Hours = 2,
  TagDeviceDataPresetLast4Hours = 3,
  TagDeviceDataPresetLast6Hours = 4,
  TagDeviceDataPresetCustom = 5,
};

SWIFT_CLASS("_TtC6TagSdk18TagDeviceDataQuery")
@interface TagDeviceDataQuery : NSObject
@property (nonatomic, readonly, strong) TagDeviceKey * _Nonnull deviceKey;
@property (nonatomic, readonly) enum TagDeviceDataPreset preset;
@property (nonatomic, readonly, strong) NSNumber * _Nullable startTimeMs;
@property (nonatomic, readonly, strong) NSNumber * _Nullable endTimeMs;
- (nonnull instancetype)initWithDeviceKey:(TagDeviceKey * _Nonnull)deviceKey preset:(enum TagDeviceDataPreset)preset startTimeMs:(NSNumber * _Nullable)startTimeMs endTimeMs:(NSNumber * _Nullable)endTimeMs OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC6TagSdk13TagDeviceInfo")
@interface TagDeviceInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull serverRecordId;
@property (nonatomic, readonly, copy) NSString * _Nullable tagDeviceId;
@property (nonatomic, readonly, copy) NSString * _Nonnull deviceName;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull macAddresses;
@property (nonatomic, readonly, strong) TagDeviceKey * _Nonnull primaryDeviceKey;
@property (nonatomic, readonly, strong) NSNumber * _Nullable batteryLevel;
@property (nonatomic, readonly, copy) NSString * _Nonnull deviceType;
@property (nonatomic, readonly, strong) NSNumber * _Nullable deviceModelRawValue;
@property (nonatomic, readonly) BOOL supportsElectronicFence;
@property (nonatomic, readonly, copy) NSString * _Nullable relationshipType;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC6TagSdk12TagDeviceKey")
@interface TagDeviceKey : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull deviceKey;
- (nonnull instancetype)initWithDeviceKey:(NSString * _Nonnull)deviceKey OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC6TagSdk22TagDeviceUpdateRequest")
@interface TagDeviceUpdateRequest : NSObject
@property (nonatomic, readonly, strong) TagDeviceKey * _Nonnull deviceKey;
@property (nonatomic, readonly, copy) NSString * _Nonnull deviceName;
@property (nonatomic, readonly, copy) NSString * _Nonnull deviceType;
- (nonnull instancetype)initWithDeviceKey:(TagDeviceKey * _Nonnull)deviceKey deviceName:(NSString * _Nonnull)deviceName deviceType:(NSString * _Nonnull)deviceType OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC6TagSdk8TagError")
@interface TagError : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull code;
@property (nonatomic, readonly, copy) NSString * _Nonnull message;
@property (nonatomic, readonly, copy) NSString * _Nullable serverCode;
@property (nonatomic, readonly, strong) NSError * _Nullable platformCause;
- (nonnull instancetype)initWithCode:(NSString * _Nonnull)code message:(NSString * _Nonnull)message serverCode:(NSString * _Nullable)serverCode platformCause:(NSError * _Nullable)platformCause OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC6TagSdk12TagErrorCode")
@interface TagErrorCode : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull notInitialized;)
+ (NSString * _Nonnull)notInitialized SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sdkAlreadyInitialized;)
+ (NSString * _Nonnull)sdkAlreadyInitialized SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull invalidArgument;)
+ (NSString * _Nonnull)invalidArgument SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull featureNotAvailable;)
+ (NSString * _Nonnull)featureNotAvailable SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull bluetoothUnavailable;)
+ (NSString * _Nonnull)bluetoothUnavailable SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull permissionDenied;)
+ (NSString * _Nonnull)permissionDenied SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull scanAlreadyRunning;)
+ (NSString * _Nonnull)scanAlreadyRunning SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull scanFailed;)
+ (NSString * _Nonnull)scanFailed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull connectionFailed;)
+ (NSString * _Nonnull)connectionFailed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull connectionTimeout;)
+ (NSString * _Nonnull)connectionTimeout SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull serviceDiscoveryFailed;)
+ (NSString * _Nonnull)serviceDiscoveryFailed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull notifyEnableFailed;)
+ (NSString * _Nonnull)notifyEnableFailed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull gattWriteFailed;)
+ (NSString * _Nonnull)gattWriteFailed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull commandTimeout;)
+ (NSString * _Nonnull)commandTimeout SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull disconnected;)
+ (NSString * _Nonnull)disconnected SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sdkReleased;)
+ (NSString * _Nonnull)sdkReleased SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull frameFormatError;)
+ (NSString * _Nonnull)frameFormatError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull payloadTooLarge;)
+ (NSString * _Nonnull)payloadTooLarge SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull checksumError;)
+ (NSString * _Nonnull)checksumError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull responseMismatch;)
+ (NSString * _Nonnull)responseMismatch SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull unknownResponse;)
+ (NSString * _Nonnull)unknownResponse SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull deviceRejected;)
+ (NSString * _Nonnull)deviceRejected SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull keyMissing;)
+ (NSString * _Nonnull)keyMissing SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull bindingUnsupported;)
+ (NSString * _Nonnull)bindingUnsupported SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull alreadyBound;)
+ (NSString * _Nonnull)alreadyBound SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull customerManagedOperation;)
+ (NSString * _Nonnull)customerManagedOperation SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull customerBindingHandlerMissing;)
+ (NSString * _Nonnull)customerBindingHandlerMissing SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull openApiCredentialMissing;)
+ (NSString * _Nonnull)openApiCredentialMissing SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull openApiDeviceKeyUnsupported;)
+ (NSString * _Nonnull)openApiDeviceKeyUnsupported SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull customerBindingRejected;)
+ (NSString * _Nonnull)customerBindingRejected SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull customerBindingTimeout;)
+ (NSString * _Nonnull)customerBindingTimeout SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull networkError;)
+ (NSString * _Nonnull)networkError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull authenticationFailed;)
+ (NSString * _Nonnull)authenticationFailed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull serverError;)
+ (NSString * _Nonnull)serverError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull logExportFailed;)
+ (NSString * _Nonnull)logExportFailed SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, TagIntegrationMode, open) {
  TagIntegrationModeOfficial = 0,
  TagIntegrationModeCustomerManaged = 1,
};

SWIFT_CLASS("_TtC6TagSdk13TagLogArchive")
@interface TagLogArchive : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull filePath;
@property (nonatomic, readonly) int64_t fileSizeBytes;
@property (nonatomic, readonly) int64_t createdAtMs;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC6TagSdk20TagLoginCapabilities")
@interface TagLoginCapabilities : NSObject
@property (nonatomic, readonly) BOOL supportsBattery;
@property (nonatomic, readonly) BOOL supportsV2Binding;
@property (nonatomic, readonly) BOOL supportsElectronicFence;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC6TagSdk15TagLoginRequest")
@interface TagLoginRequest : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull username;
@property (nonatomic, readonly, copy) NSString * _Nonnull password;
- (nonnull instancetype)initWithUsername:(NSString * _Nonnull)username password:(NSString * _Nonnull)password OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC6TagSdk20TagOpenApiCredential")
@interface TagOpenApiCredential : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull apiKey;
@property (nonatomic, readonly, copy) NSString * _Nonnull apiSecret;
- (nonnull instancetype)initWithApiKey:(NSString * _Nonnull)apiKey apiSecret:(NSString * _Nonnull)apiSecret OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC6TagSdk18TagRegisterRequest")
@interface TagRegisterRequest : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull username;
@property (nonatomic, readonly, copy) NSString * _Nonnull password;
- (nonnull instancetype)initWithUsername:(NSString * _Nonnull)username password:(NSString * _Nonnull)password OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, TagScanFinishReason, open) {
  TagScanFinishReasonTimeout = 0,
  TagScanFinishReasonStopped = 1,
  TagScanFinishReasonOperationStarted = 2,
};

SWIFT_PROTOCOL("_TtP6TagSdk15TagScanListener_")
@protocol TagScanListener
- (void)onDeviceFound:(TagDevice * _Nonnull)device;
- (void)onScanFinished:(enum TagScanFinishReason)reason;
- (void)onScanFailed:(TagError * _Nonnull)error;
@end

SWIFT_CLASS("_TtC6TagSdk14TagScanOptions")
@interface TagScanOptions : NSObject
@property (nonatomic, readonly) int64_t timeoutMs;
- (nonnull instancetype)initWithTimeoutMs:(int64_t)timeoutMs OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class TagSdkConfig;
@protocol TagSubscription;
SWIFT_CLASS("_TtC6TagSdk6TagSdk")
@interface TagSdk : NSObject
+ (TagError * _Nullable)initializeWithConfig:(TagSdkConfig * _Nonnull)config SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getSdkVersion SWIFT_WARN_UNUSED_RESULT;
+ (void)setLogEnabled:(BOOL)enabled;
+ (void)exportLogs:(void (^ _Nonnull)(TagLogArchive * _Nullable, TagError * _Nullable))completion;
+ (id <TagSubscription> _Nonnull)startScanWithOptions:(TagScanOptions * _Nonnull)options listener:(id <TagScanListener> _Nonnull)listener SWIFT_WARN_UNUSED_RESULT;
+ (void)stopScan;
+ (id <TagSubscription> _Nonnull)observeBluetoothState:(id <TagBluetoothStateListener> _Nonnull)listener SWIFT_WARN_UNUSED_RESULT;
+ (void)connectAndBindDevice:(TagDevice * _Nonnull)device completion:(void (^ _Nonnull)(TagBindingInfo * _Nullable, TagError * _Nullable))completion;
+ (void)findDevice:(TagDevice * _Nonnull)device completion:(void (^ _Nonnull)(FindDeviceResult * _Nullable, TagError * _Nullable))completion;
+ (void)register:(TagRegisterRequest * _Nonnull)request completion:(void (^ _Nonnull)(TagAccount * _Nullable, TagError * _Nullable))completion;
+ (void)login:(TagLoginRequest * _Nonnull)request completion:(void (^ _Nonnull)(TagAccount * _Nullable, TagError * _Nullable))completion;
+ (TagAccount * _Nullable)getCurrentAccount SWIFT_WARN_UNUSED_RESULT;
+ (void)logout;
+ (void)getDeviceList:(void (^ _Nonnull)(NSArray<TagDeviceInfo *> * _Nullable, TagError * _Nullable))completion;
+ (void)updateDeviceInfo:(TagDeviceUpdateRequest * _Nonnull)request completion:(void (^ _Nonnull)(NSNumber * _Nullable, TagError * _Nullable))completion;
+ (void)unbindDevice:(TagDeviceKey * _Nonnull)key completion:(void (^ _Nonnull)(NSNumber * _Nullable, TagError * _Nullable))completion;
+ (void)getDeviceData:(TagDeviceDataQuery * _Nonnull)query completion:(void (^ _Nonnull)(NSArray<TagDeviceData *> * _Nullable, TagError * _Nullable))completion;
+ (void)releaseSdk;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC6TagSdk12TagSdkConfig")
@interface TagSdkConfig : NSObject
@property (nonatomic, readonly) enum TagIntegrationMode integrationMode;
@property (nonatomic, readonly, strong) TagOpenApiCredential * _Nullable openApiCredential;
@property (nonatomic, readonly) int64_t customerBindingTimeoutMs;
@property (nonatomic, readonly, strong) id <CustomerBindingHandler> _Nullable customerBindingHandler;
@property (nonatomic, readonly) BOOL logEnabled;
- (nonnull instancetype)initWithIntegrationMode:(enum TagIntegrationMode)integrationMode openApiCredential:(TagOpenApiCredential * _Nullable)openApiCredential customerBindingTimeoutMs:(int64_t)customerBindingTimeoutMs customerBindingHandler:(id <CustomerBindingHandler> _Nullable)customerBindingHandler logEnabled:(BOOL)logEnabled OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_PROTOCOL("_TtP6TagSdk15TagSubscription_")
@protocol TagSubscription
- (void)cancel;
@end

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.3.2 effective-5.10 (swiftlang-6.3.2.1.108 clang-2100.1.1.101)
#ifndef TAGSDK_SWIFT_H
#define TAGSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="TagSdk",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="TagSdk",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class TagCustomerBindingRequest;
@protocol TagCustomerBindingCompletion;
SWIFT_PROTOCOL("_TtP6TagSdk22CustomerBindingHandler_")
@protocol CustomerBindingHandler
- (void)bind:(TagCustomerBindingRequest * _Nonnull)request completion:(id <TagCustomerBindingCompletion> _Nonnull)completion;
@end

@class NSString;
@class TagLoginCapabilities;
@class TagBatteryInfo;
SWIFT_CLASS("_TtC6TagSdk16FindDeviceResult")
@interface FindDeviceResult : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull scanDeviceId;
@property (nonatomic, readonly) BOOL triggered;
@property (nonatomic, readonly, strong) TagLoginCapabilities * _Nullable capabilities;
@property (nonatomic, readonly, strong) TagBatteryInfo * _Nullable battery;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSCoder;
SWIFT_CLASS("_TtC6TagSdk10TagAccount")
@interface TagAccount : NSObject <NSSecureCoding>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL supportsSecureCoding;)
+ (BOOL)supportsSecureCoding SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull accountId;
@property (nonatomic, readonly, copy) NSString * _Nonnull username;
@property (nonatomic, readonly, copy) NSString * _Nullable nickname;
@property (nonatomic, readonly, copy) NSString * _Nullable email;
- (nonnull instancetype)initWithAccountId:(NSString * _Nonnull)accountId username:(NSString * _Nonnull)username nickname:(NSString * _Nullable)nickname email:(NSString * _Nullable)email OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)coder;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC6TagSdk14TagBatteryInfo")
@interface TagBatteryInfo : NSObject
@property (nonatomic, readonly) NSInteger rawBattery;
@property (nonatomic, readonly) NSInteger serverLevel;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class TagDeviceKey;
SWIFT_CLASS("_TtC6TagSdk14TagBindingInfo")
@interface TagBindingInfo : NSObject
@property (nonatomic, readonly, strong) TagDeviceKey * _Nonnull primaryDeviceKey;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, TagBluetoothState, open) {
  TagBluetoothStateUnknown = 0,
  TagBluetoothStatePoweredOff = 1,
  TagBluetoothStatePoweredOn = 2,
  TagBluetoothStateUnauthorized = 3,
};

SWIFT_PROTOCOL("_TtP6TagSdk25TagBluetoothStateListener_")
@protocol TagBluetoothStateListener
- (void)onStateChanged:(enum TagBluetoothState)state;
@end

@class TagCustomerBindingDecision;
SWIFT_PROTOCOL("_TtP6TagSdk28TagCustomerBindingCompletion_")
@protocol TagCustomerBindingCompletion
- (void)complete:(TagCustomerBindingDecision * _Nonnull)decision;
@end

@class TagCustomerBindingError;
SWIFT_CLASS("_TtC6TagSdk26TagCustomerBindingDecision")
@interface TagCustomerBindingDecision : NSObject
@property (nonatomic, readonly) BOOL isApproved;
@property (nonatomic, readonly, strong) TagCustomerBindingError * _Nullable error;
+ (TagCustomerBindingDecision * _Nonnull)approved SWIFT_WARN_UNUSED_RESULT;
+ (TagCustomerBindingDecision * _Nonnull)rejected:(TagCustomerBindingError * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSError;
SWIFT_CLASS("_TtC6TagSdk23TagCustomerBindingError")
@interface TagCustomerBindingError : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable message;
@property (nonatomic, readonly, strong) NSError * _Nullable platformCause;
- (nonnull instancetype)initWithMessage:(NSString * _Nullable)message platformCause:(NSError * _Nullable)platformCause OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC6TagSdk25TagCustomerBindingRequest")
@interface TagCustomerBindingRequest : NSObject
@property (nonatomic, readonly, strong) TagBindingInfo * _Nonnull bindingInfo;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC6TagSdk9TagDevice")
@interface TagDevice : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic, readonly, copy) NSString * _Nullable name;
@property (nonatomic, readonly) NSInteger rssi;
@property (nonatomic, readonly, copy) NSString * _Nullable platformAddress;
@property (nonatomic, readonly, copy) NSString * _Nullable advertisedMac;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSNumber;
SWIFT_CLASS("_TtC6TagSdk13TagDeviceData")
@interface TagDeviceData : NSObject
@property (nonatomic, readonly, strong) TagDeviceKey * _Nonnull deviceKey;
@property (nonatomic, readonly) int64_t collectionTimeMs;
@property (nonatomic, readonly) double longitude;
@property (nonatomic, readonly) double latitude;
@property (nonatomic, readonly, strong) NSNumber * _Nullable batteryLevel;
@property (nonatomic, readonly, strong) NSNumber * _Nullable accuracyLevel;
@property (nonatomic, readonly) BOOL googleLocation;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, TagDeviceDataPreset, open) {
  TagDeviceDataPresetLatest = 0,
  TagDeviceDataPresetLast1Hour = 1,
  TagDeviceDataPresetLast2Hours = 2,
  TagDeviceDataPresetLast4Hours = 3,
  TagDeviceDataPresetLast6Hours = 4,
  TagDeviceDataPresetCustom = 5,
};

SWIFT_CLASS("_TtC6TagSdk18TagDeviceDataQuery")
@interface TagDeviceDataQuery : NSObject
@property (nonatomic, readonly, strong) TagDeviceKey * _Nonnull deviceKey;
@property (nonatomic, readonly) enum TagDeviceDataPreset preset;
@property (nonatomic, readonly, strong) NSNumber * _Nullable startTimeMs;
@property (nonatomic, readonly, strong) NSNumber * _Nullable endTimeMs;
- (nonnull instancetype)initWithDeviceKey:(TagDeviceKey * _Nonnull)deviceKey preset:(enum TagDeviceDataPreset)preset startTimeMs:(NSNumber * _Nullable)startTimeMs endTimeMs:(NSNumber * _Nullable)endTimeMs OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC6TagSdk13TagDeviceInfo")
@interface TagDeviceInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull serverRecordId;
@property (nonatomic, readonly, copy) NSString * _Nullable tagDeviceId;
@property (nonatomic, readonly, copy) NSString * _Nonnull deviceName;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull macAddresses;
@property (nonatomic, readonly, strong) TagDeviceKey * _Nonnull primaryDeviceKey;
@property (nonatomic, readonly, strong) NSNumber * _Nullable batteryLevel;
@property (nonatomic, readonly, copy) NSString * _Nonnull deviceType;
@property (nonatomic, readonly, strong) NSNumber * _Nullable deviceModelRawValue;
@property (nonatomic, readonly) BOOL supportsElectronicFence;
@property (nonatomic, readonly, copy) NSString * _Nullable relationshipType;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC6TagSdk12TagDeviceKey")
@interface TagDeviceKey : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull deviceKey;
- (nonnull instancetype)initWithDeviceKey:(NSString * _Nonnull)deviceKey OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC6TagSdk22TagDeviceUpdateRequest")
@interface TagDeviceUpdateRequest : NSObject
@property (nonatomic, readonly, strong) TagDeviceKey * _Nonnull deviceKey;
@property (nonatomic, readonly, copy) NSString * _Nonnull deviceName;
@property (nonatomic, readonly, copy) NSString * _Nonnull deviceType;
- (nonnull instancetype)initWithDeviceKey:(TagDeviceKey * _Nonnull)deviceKey deviceName:(NSString * _Nonnull)deviceName deviceType:(NSString * _Nonnull)deviceType OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC6TagSdk8TagError")
@interface TagError : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull code;
@property (nonatomic, readonly, copy) NSString * _Nonnull message;
@property (nonatomic, readonly, copy) NSString * _Nullable serverCode;
@property (nonatomic, readonly, strong) NSError * _Nullable platformCause;
- (nonnull instancetype)initWithCode:(NSString * _Nonnull)code message:(NSString * _Nonnull)message serverCode:(NSString * _Nullable)serverCode platformCause:(NSError * _Nullable)platformCause OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC6TagSdk12TagErrorCode")
@interface TagErrorCode : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull notInitialized;)
+ (NSString * _Nonnull)notInitialized SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sdkAlreadyInitialized;)
+ (NSString * _Nonnull)sdkAlreadyInitialized SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull invalidArgument;)
+ (NSString * _Nonnull)invalidArgument SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull featureNotAvailable;)
+ (NSString * _Nonnull)featureNotAvailable SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull bluetoothUnavailable;)
+ (NSString * _Nonnull)bluetoothUnavailable SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull permissionDenied;)
+ (NSString * _Nonnull)permissionDenied SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull scanAlreadyRunning;)
+ (NSString * _Nonnull)scanAlreadyRunning SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull scanFailed;)
+ (NSString * _Nonnull)scanFailed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull connectionFailed;)
+ (NSString * _Nonnull)connectionFailed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull connectionTimeout;)
+ (NSString * _Nonnull)connectionTimeout SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull serviceDiscoveryFailed;)
+ (NSString * _Nonnull)serviceDiscoveryFailed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull notifyEnableFailed;)
+ (NSString * _Nonnull)notifyEnableFailed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull gattWriteFailed;)
+ (NSString * _Nonnull)gattWriteFailed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull commandTimeout;)
+ (NSString * _Nonnull)commandTimeout SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull disconnected;)
+ (NSString * _Nonnull)disconnected SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sdkReleased;)
+ (NSString * _Nonnull)sdkReleased SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull frameFormatError;)
+ (NSString * _Nonnull)frameFormatError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull payloadTooLarge;)
+ (NSString * _Nonnull)payloadTooLarge SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull checksumError;)
+ (NSString * _Nonnull)checksumError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull responseMismatch;)
+ (NSString * _Nonnull)responseMismatch SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull unknownResponse;)
+ (NSString * _Nonnull)unknownResponse SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull deviceRejected;)
+ (NSString * _Nonnull)deviceRejected SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull keyMissing;)
+ (NSString * _Nonnull)keyMissing SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull bindingUnsupported;)
+ (NSString * _Nonnull)bindingUnsupported SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull alreadyBound;)
+ (NSString * _Nonnull)alreadyBound SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull customerManagedOperation;)
+ (NSString * _Nonnull)customerManagedOperation SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull customerBindingHandlerMissing;)
+ (NSString * _Nonnull)customerBindingHandlerMissing SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull openApiCredentialMissing;)
+ (NSString * _Nonnull)openApiCredentialMissing SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull openApiDeviceKeyUnsupported;)
+ (NSString * _Nonnull)openApiDeviceKeyUnsupported SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull customerBindingRejected;)
+ (NSString * _Nonnull)customerBindingRejected SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull customerBindingTimeout;)
+ (NSString * _Nonnull)customerBindingTimeout SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull networkError;)
+ (NSString * _Nonnull)networkError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull authenticationFailed;)
+ (NSString * _Nonnull)authenticationFailed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull serverError;)
+ (NSString * _Nonnull)serverError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull logExportFailed;)
+ (NSString * _Nonnull)logExportFailed SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, TagIntegrationMode, open) {
  TagIntegrationModeOfficial = 0,
  TagIntegrationModeCustomerManaged = 1,
};

SWIFT_CLASS("_TtC6TagSdk13TagLogArchive")
@interface TagLogArchive : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull filePath;
@property (nonatomic, readonly) int64_t fileSizeBytes;
@property (nonatomic, readonly) int64_t createdAtMs;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC6TagSdk20TagLoginCapabilities")
@interface TagLoginCapabilities : NSObject
@property (nonatomic, readonly) BOOL supportsBattery;
@property (nonatomic, readonly) BOOL supportsV2Binding;
@property (nonatomic, readonly) BOOL supportsElectronicFence;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC6TagSdk15TagLoginRequest")
@interface TagLoginRequest : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull username;
@property (nonatomic, readonly, copy) NSString * _Nonnull password;
- (nonnull instancetype)initWithUsername:(NSString * _Nonnull)username password:(NSString * _Nonnull)password OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC6TagSdk20TagOpenApiCredential")
@interface TagOpenApiCredential : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull apiKey;
@property (nonatomic, readonly, copy) NSString * _Nonnull apiSecret;
- (nonnull instancetype)initWithApiKey:(NSString * _Nonnull)apiKey apiSecret:(NSString * _Nonnull)apiSecret OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC6TagSdk18TagRegisterRequest")
@interface TagRegisterRequest : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull username;
@property (nonatomic, readonly, copy) NSString * _Nonnull password;
- (nonnull instancetype)initWithUsername:(NSString * _Nonnull)username password:(NSString * _Nonnull)password OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, TagScanFinishReason, open) {
  TagScanFinishReasonTimeout = 0,
  TagScanFinishReasonStopped = 1,
  TagScanFinishReasonOperationStarted = 2,
};

SWIFT_PROTOCOL("_TtP6TagSdk15TagScanListener_")
@protocol TagScanListener
- (void)onDeviceFound:(TagDevice * _Nonnull)device;
- (void)onScanFinished:(enum TagScanFinishReason)reason;
- (void)onScanFailed:(TagError * _Nonnull)error;
@end

SWIFT_CLASS("_TtC6TagSdk14TagScanOptions")
@interface TagScanOptions : NSObject
@property (nonatomic, readonly) int64_t timeoutMs;
- (nonnull instancetype)initWithTimeoutMs:(int64_t)timeoutMs OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class TagSdkConfig;
@protocol TagSubscription;
SWIFT_CLASS("_TtC6TagSdk6TagSdk")
@interface TagSdk : NSObject
+ (TagError * _Nullable)initializeWithConfig:(TagSdkConfig * _Nonnull)config SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getSdkVersion SWIFT_WARN_UNUSED_RESULT;
+ (void)setLogEnabled:(BOOL)enabled;
+ (void)exportLogs:(void (^ _Nonnull)(TagLogArchive * _Nullable, TagError * _Nullable))completion;
+ (id <TagSubscription> _Nonnull)startScanWithOptions:(TagScanOptions * _Nonnull)options listener:(id <TagScanListener> _Nonnull)listener SWIFT_WARN_UNUSED_RESULT;
+ (void)stopScan;
+ (id <TagSubscription> _Nonnull)observeBluetoothState:(id <TagBluetoothStateListener> _Nonnull)listener SWIFT_WARN_UNUSED_RESULT;
+ (void)connectAndBindDevice:(TagDevice * _Nonnull)device completion:(void (^ _Nonnull)(TagBindingInfo * _Nullable, TagError * _Nullable))completion;
+ (void)findDevice:(TagDevice * _Nonnull)device completion:(void (^ _Nonnull)(FindDeviceResult * _Nullable, TagError * _Nullable))completion;
+ (void)register:(TagRegisterRequest * _Nonnull)request completion:(void (^ _Nonnull)(TagAccount * _Nullable, TagError * _Nullable))completion;
+ (void)login:(TagLoginRequest * _Nonnull)request completion:(void (^ _Nonnull)(TagAccount * _Nullable, TagError * _Nullable))completion;
+ (TagAccount * _Nullable)getCurrentAccount SWIFT_WARN_UNUSED_RESULT;
+ (void)logout;
+ (void)getDeviceList:(void (^ _Nonnull)(NSArray<TagDeviceInfo *> * _Nullable, TagError * _Nullable))completion;
+ (void)updateDeviceInfo:(TagDeviceUpdateRequest * _Nonnull)request completion:(void (^ _Nonnull)(NSNumber * _Nullable, TagError * _Nullable))completion;
+ (void)unbindDevice:(TagDeviceKey * _Nonnull)key completion:(void (^ _Nonnull)(NSNumber * _Nullable, TagError * _Nullable))completion;
+ (void)getDeviceData:(TagDeviceDataQuery * _Nonnull)query completion:(void (^ _Nonnull)(NSArray<TagDeviceData *> * _Nullable, TagError * _Nullable))completion;
+ (void)releaseSdk;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC6TagSdk12TagSdkConfig")
@interface TagSdkConfig : NSObject
@property (nonatomic, readonly) enum TagIntegrationMode integrationMode;
@property (nonatomic, readonly, strong) TagOpenApiCredential * _Nullable openApiCredential;
@property (nonatomic, readonly) int64_t customerBindingTimeoutMs;
@property (nonatomic, readonly, strong) id <CustomerBindingHandler> _Nullable customerBindingHandler;
@property (nonatomic, readonly) BOOL logEnabled;
- (nonnull instancetype)initWithIntegrationMode:(enum TagIntegrationMode)integrationMode openApiCredential:(TagOpenApiCredential * _Nullable)openApiCredential customerBindingTimeoutMs:(int64_t)customerBindingTimeoutMs customerBindingHandler:(id <CustomerBindingHandler> _Nullable)customerBindingHandler logEnabled:(BOOL)logEnabled OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_PROTOCOL("_TtP6TagSdk15TagSubscription_")
@protocol TagSubscription
- (void)cancel;
@end

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
